services:
  # Backend Service
  - type: web
    name: smartcards-ai-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: smartcards-ai-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://smartcards-ai-backend.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production
    autoDeploy: true 