-- YES Bank Credit Cards Population Script
-- Generated: December 2024
-- Total Cards: 8
-- Bank Focus: Premium lifestyle, innovative banking, digital-first approach

-- Insert YES Bank Cards
INSERT INTO card_master_data (
    bank_name, card_name, card_variant, annual_fee, joining_fee, 
    minimum_age, maximum_age, minimum_salary, card_network, card_tier,
    is_lifetime_free, foreign_transaction_fee, late_payment_fee,
    contactless_enabled, chip_enabled, mobile_wallet_support,
    domestic_lounge_visits, international_lounge_visits,
    welcome_bonus_points, minimum_credit_limit, maximum_credit_limit,
    insurance_benefits, concierge_service
) VALUES

-- 1. YES Bank Marquee Credit Card
('YES Bank', 'Marquee Credit Card', 'Super-Premium', 4999, 9999,
 21, 60, 3600000, 750,
 'Unlimited international lounge access, premium rewards, golf benefits, movie offers',
 '36 YES Rewardz Points per Rs. 200 on online shopping, 18 points per Rs. 200 on offline spends',
 'Yes - 24 domestic (6 per quarter) and unlimited international lounge access',
 'Credit shield cover Rs. 15 lakh, purchase protection Rs. 50,000 for 6 months',
 4.5, 'Yes - 1% fuel surcharge waiver up to Rs. 1000 monthly',
 'Yes - 1% forex markup, global priority services',
 'Yes', 'Yes', 'Yes',
 'Up to 4.5% reward rate on online shopping, no category restrictions',
 'Unlimited international lounge access, low forex markup, travel insurance',
 '15% discount at select restaurants under Dining Fiesta program',
 'Buy 1 Get 1 movie tickets up to Rs. 800, max 3 free tickets monthly',
 'Rewards on all merchant types including typically excluded categories',
 'Reward points on utility bills, insurance, rent, and government payments',
 '20,000 bonus YES Rewardz Points on renewal fee payment',
 '40,000 YES Rewardz Points + complimentary ETPrime subscription worth Rs. 3,199',
 1.0, 'Rs. 1350 or 10% of outstanding', 'Rs. 750 or 3% of overlimit amount',
 '2.99% of amount advanced', '35.88', '35.88', '35.88',
 5, 'Premium limit enhancement for high spenders',
 'Free for add-on cards', 'High-income salaried/self-employed', 'ITR showing min Rs. 36 lakh p.a. or monthly income Rs. 3 lakh',
 '5-7 working days', '5-7 working days', 'Yes',
 'Premium customer support, dedicated relationship manager', 4.5,
 'Advanced fraud protection, premium transaction monitoring',
 'Rewards on all categories including wallet, rent, insurance payments',
 1000000, 'Visa Infinite - premium global acceptance',
 datetime('now'), datetime('now')),

-- 2. YES Bank Prosperity Credit Card
('YES Bank', 'Prosperity Credit Card', 'Premium', 2999, 2999,
 21, 60, 1200000, 700,
 'Premium lifestyle benefits, lounge access, dining privileges, travel rewards',
 '2 YES Rewardz Points per Rs. 100 spent, 4 points on dining and travel',
 'Yes - 12 domestic lounge visits per year',
 'Travel insurance up to Rs. 25 lakh, personal accident cover Rs. 10 lakh',
 2.0, 'Yes - 1% fuel surcharge waiver up to Rs. 500 monthly',
 'Yes - 2.5% forex markup, international acceptance',
 'Yes', 'Yes', 'Yes',
 'Premium online shopping rewards, exclusive brand partnerships',
 'Lounge access, travel insurance, hotel booking discounts',
 'Premium dining experiences, up to 20% discount at partner restaurants',
 'Movie ticket discounts, entertainment venue partnerships',
 'Premium grocery chain partnerships',
 'Priority bill payment services, reward points on utilities',
 '10,000 bonus YES Rewardz Points on annual renewal',
 '15,000 welcome YES Rewardz Points + lifestyle vouchers',
 2.5, 'Rs. 750 or 3% of total due', 'Rs. 600 or 2.75% of overlimit amount',
 '3.0% of amount advanced', '18.00', '18.00', '47.40',
 4, 'Premium automatic limit enhancement',
 399, 'Affluent salaried/self-employed', 'Income proof showing min Rs. 12 lakh p.a.',
 '7-10 working days', '7-10 working days', 'Yes',
 'Premium customer support, lifestyle concierge', 4.3,
 'Enhanced security features, premium fraud monitoring',
 'Standard restrictions on cash advance and certain merchants',
 500000, 'Visa Signature - premium global network',
 datetime('now'), datetime('now')),

-- 3. YES Bank Wellness Credit Card
('YES Bank', 'Wellness Credit Card', 'Lifestyle-Health', 1999, 1999,
 21, 60, 600000, 650,
 'Health and wellness rewards, fitness benefits, medical coverage, lifestyle perks',
 '5 YES Rewardz Points per Rs. 100 on health and wellness spends, 2 points on other purchases',
 'Yes - 6 domestic lounge visits per year',
 'Health insurance top-up Rs. 5 lakh, wellness accident cover',
 2.5, 'Yes - 1% fuel surcharge waiver for health-related travel',
 'Yes - wellness-focused international benefits, medical tourism support',
 'Yes', 'Yes', 'Yes',
 'Health and wellness e-commerce rewards, supplement store benefits',
 'Medical tourism packages, wellness retreat discounts',
 'Healthy dining options, nutrition-focused restaurant partnerships',
 'Health documentaries and wellness content subscriptions',
 'Organic and health food store exclusive partnerships',
 'Health insurance premium payment benefits',
 'Wellness vouchers and health checkup credits worth Rs. 5,000',
 'Health and wellness starter pack + 8,000 welcome points',
 2.75, 'Rs. 650 or 2.75% of total due', 'Rs. 500 or 2.5% of overlimit amount',
 '3.0% of amount advanced', '17.50', '17.50', '45.00',
 4, 'Health goal achievement-based enhancements',
 299, 'Health-conscious professionals', 'Standard documents + health insurance preference',
 '7-10 working days', '7-10 working days', 'Yes',
 'Health-focused customer support, wellness guidance', 4.1,
 'Health data security, wellness spending monitoring',
 'Enhanced rewards only on genuine health and wellness merchants',
 300000, 'Mastercard - wellness partner network',
 datetime('now'), datetime('now')),

-- 4. YES Bank First Exclusive Credit Card
('YES Bank', 'First Exclusive Credit Card', 'Premium-Exclusive', 5999, 5999,
 25, 65, 1800000, 750,
 'Exclusive privileges, invitation-only benefits, premium concierge, luxury experiences',
 '3 YES Rewardz Points per Rs. 100 spent, 6 points on luxury and international spends',
 'Yes - 16 domestic and 8 international lounge visits per year',
 'Exclusive travel insurance Rs. 50 lakh, luxury lifestyle protection',
 3.0, 'Yes - 2% fuel surcharge waiver up to Rs. 2000 monthly',
 'Yes - 1.5% forex markup, exclusive global privileges',
 'Yes', 'Yes', 'Yes',
 'Exclusive luxury brand shopping experiences, VIP access',
 'Premium travel concierge, luxury hotel partnerships, exclusive experiences',
 'Michelin-starred restaurant access, celebrity chef experiences',
 'Exclusive premiere access, private screenings, film festival invitations',
 'Gourmet grocery services, premium food delivery partnerships',
 'Concierge-managed utility and lifestyle services',
 '30,000 bonus YES Rewardz Points + exclusive experiences worth Rs. 15,000',
 '50,000 welcome YES Rewardz Points + luxury welcome package',
 1.5, 'Rs. 900 or 3.5% of total due', 'Rs. 700 or 3% of overlimit amount',
 '2.5% of amount advanced', '15.00', '15.00', '42.00',
 6, 'Exclusive automatic enhancement for luxury spenders',
 'Free for immediate family', 'High net worth individuals, exclusive banking clients',
 'Wealth verification, exclusive banking relationship, lifestyle assessment',
 '3-5 working days', '3-5 working days', 'Yes',
 'Dedicated relationship manager, exclusive concierge services', 4.6,
 'Luxury-grade security, exclusive fraud protection, priority resolution',
 'Focus on luxury merchants, exclusive brand partnerships',
 1500000, 'Visa Infinite - exclusive global network',
 datetime('now'), datetime('now')),

-- 5. YES Bank Premia Credit Card
('YES Bank', 'Premia Credit Card', 'Mid-Premium', 1499, 1499,
 21, 60, 500000, 650,
 'Balanced premium benefits, travel perks, lifestyle rewards, value-focused',
 '2 YES Rewardz Points per Rs. 100 spent, 3 points on travel and dining',
 'Yes - 8 domestic lounge visits per year',
 'Travel insurance Rs. 15 lakh, personal accident cover Rs. 8 lakh',
 2.0, 'Yes - 1% fuel surcharge waiver up to Rs. 750 monthly',
 'Yes - 2.75% forex markup, reliable international usage',
 'Yes', 'Yes', 'Yes',
 'Premium online shopping rewards, seasonal offers',
 'Airport lounge access, travel booking assistance, insurance coverage',
 'Premium dining discounts up to 15% at partner restaurants',
 'Movie ticket offers, entertainment discounts',
 'Premium grocery store partnerships and seasonal offers',
 'Utility bill payment rewards and convenience',
 '6,000 bonus YES Rewardz Points on annual renewal',
 '8,000 welcome YES Rewardz Points + lifestyle vouchers',
 2.75, 'Rs. 650 or 2.75% of total due', 'Rs. 500 or 2.5% of overlimit amount',
 '3.0% of amount advanced', '17.00', '17.00', '45.50',
 4, 'Regular limit enhancement for good payment history',
 299, 'Mid-income salaried/self-employed', 'Standard income documents, min Rs. 5 lakh p.a.',
 '8-12 working days', '8-12 working days', 'Yes',
 'Standard premium support, lifestyle assistance', 4.0,
 'Standard premium security, transaction monitoring',
 'Standard premium merchant access',
 350000, 'Visa/Mastercard - reliable global acceptance',
 datetime('now'), datetime('now')),

-- 6. YES Bank Kisan Credit Card
('YES Bank', 'Kisan Credit Card', 'Agricultural', 500, 0,
 21, 70, 100000, 550,
 'Agricultural focus, farmer benefits, rural banking, crop insurance',
 '2 YES Rewardz Points per Rs. 100 on agricultural spends, 1 point on other purchases',
 'No', 'Crop insurance and agricultural accident coverage',
 1.0, 'Yes - 1% fuel surcharge waiver for agricultural vehicles',
 'Limited - focus on domestic agricultural needs',
 'Yes', 'Yes', 'Limited',
 'Agricultural equipment and supply e-commerce benefits',
 'Agricultural exhibition and training program travel benefits',
 'Rural dining and local restaurant partnerships',
 'Agricultural documentary and educational content access',
 'Organic farming and rural grocery store partnerships',
 'Agricultural utility and equipment payment benefits',
 'Agricultural equipment vouchers worth Rs. 2,000 on renewal',
 'Agricultural starter pack + 3,000 welcome points',
 3.5, 'Rs. 400 or 2% of total due', 'Rs. 300 or 2% of overlimit amount',
 '3.5% of amount advanced', '19.00', '19.00', '48.00',
 2, 'Crop yield and agricultural income-based enhancements',
 'Free', 'Farmers, agricultural professionals', 'Land ownership proof, agricultural income documents',
 '10-15 working days', '10-15 working days', 'Limited',
 'Agricultural-focused support, rural banking assistance', 3.8,
 'Rural security features, agricultural fraud monitoring',
 'Focus on agricultural and rural merchants',
 75000, 'RuPay - rural India optimized',
 datetime('now'), datetime('now')),

-- 7. YES Bank Business Credit Card
('YES Bank', 'Business Credit Card', 'Corporate', 2000, 2000,
 25, 65, 1000000, 700,
 'Business expense management, corporate rewards, B2B benefits, professional banking',
 '2.5 YES Rewardz Points per Rs. 100 on business spends, 4 points on business travel',
 'Yes - 10 domestic and 4 international lounge visits per year',
 'Business travel insurance Rs. 25 lakh, corporate liability coverage',
 2.5, 'Yes - Corporate fuel program with 2% waiver up to Rs. 3000',
 'Yes - Business-optimized international usage, corporate forex rates',
 'Yes', 'Yes', 'Yes',
 'B2B marketplace rewards, corporate vendor partnerships',
 'Corporate travel management, business hotel partnerships',
 'Business dining and client entertainment benefits',
 'Corporate event bookings and business entertainment',
 'Office supplies and corporate catering partnerships',
 'Business utility management and corporate bill payment benefits',
 'Business services credits worth Rs. 10,000 annually',
 'Corporate starter package + 15,000 welcome points',
 2.25, 'Rs. 750 or 3% of total due', 'Rs. 600 or 2.75% of overlimit amount',
 '2.75% of amount advanced', '15.50', '15.50', '43.00',
 6, 'Business growth-based automatic limit enhancements',
 499, 'Business owners, corporate professionals', 'Business registration, GST documents, financial statements',
 '5-8 working days', '5-8 working days', 'Yes',
 'Dedicated business support, corporate account management', 4.2,
 'Business-grade security, corporate expense monitoring',
 'Business-focused, enhanced corporate merchant access',
 1000000, 'Visa/Mastercard - corporate global acceptance',
 datetime('now'), datetime('now')),

-- 8. YES Bank Ace Credit Card
('YES Bank', 'Ace Credit Card', 'Entry-Level', 500, 500,
 21, 65, 240000, 600,
 'Entry-level benefits, basic rewards, affordable banking, simple features',
 '1 YES Rewardz Point per Rs. 100 spent, 2 points on online and weekend spends',
 'No', 'Basic personal accident coverage up to Rs. 3 lakh',
 1.0, 'No', 'Yes - basic international acceptance',
 'Yes', 'Yes', 'Yes',
 'Basic online shopping offers, entry-level e-commerce benefits',
 'Basic travel insurance, standard booking assistance',
 'Entry-level dining offers at budget-friendly restaurants',
 'Basic movie ticket discounts during promotional periods',
 'Basic grocery store partnerships',
 'Standard utility bill payment features',
 '1,000 bonus YES Rewardz Points on renewal',
 '2,000 welcome YES Rewardz Points on activation',
 3.5, 'Rs. 450 or 2.5% of total due', 'Rs. 350 or 2.5% of overlimit amount',
 '3.5% of amount advanced', '18.50', '18.50', '47.50',
 3, 'Basic limit enhancement after satisfactory usage',
 149, 'Entry-level salaried, young professionals', 'Basic income and identity documents',
 '10-14 working days', '10-14 working days', 'Yes',
 'Basic customer support, standard assistance', 3.7,
 'Basic security features, entry-level fraud monitoring',
 'Limited rewards on certain categories, basic merchant access',
 100000, 'Visa/Mastercard - standard global acceptance',
 datetime('now'), datetime('now'));

-- Insert YES Bank Spending Categories
INSERT INTO spending_categories (bank_name, card_name, category_name, reward_rate, monthly_cap, annual_cap) VALUES
('YES Bank', 'Marquee Credit Card', 'Online Shopping', '36 points per Rs. 200', NULL, 1200000),
('YES Bank', 'Marquee Credit Card', 'Offline Spends', '18 points per Rs. 200', NULL, NULL),
('YES Bank', 'Marquee Credit Card', 'Restricted Categories', '10 points per Rs. 200', NULL, NULL),

('YES Bank', 'Prosperity Credit Card', 'Dining', '4 points per Rs. 100', 25000, 300000),
('YES Bank', 'Prosperity Credit Card', 'Travel', '4 points per Rs. 100', 40000, 480000),
('YES Bank', 'Prosperity Credit Card', 'All Other Spends', '2 points per Rs. 100', NULL, NULL),

('YES Bank', 'Wellness Credit Card', 'Health & Wellness', '5 points per Rs. 100', 30000, 360000),
('YES Bank', 'Wellness Credit Card', 'Fitness & Sports', '5 points per Rs. 100', 20000, 240000),
('YES Bank', 'Wellness Credit Card', 'All Other Purchases', '2 points per Rs. 100', NULL, NULL),

('YES Bank', 'First Exclusive Credit Card', 'Luxury Spends', '6 points per Rs. 100', 100000, 1200000),
('YES Bank', 'First Exclusive Credit Card', 'International Transactions', '6 points per Rs. 100', NULL, NULL),
('YES Bank', 'First Exclusive Credit Card', 'All Other Spends', '3 points per Rs. 100', NULL, NULL),

('YES Bank', 'Premia Credit Card', 'Travel & Dining', '3 points per Rs. 100', 20000, 240000),
('YES Bank', 'Premia Credit Card', 'All Other Spends', '2 points per Rs. 100', NULL, NULL),

('YES Bank', 'Kisan Credit Card', 'Agricultural Spends', '2 points per Rs. 100', 10000, 120000),
('YES Bank', 'Kisan Credit Card', 'All Other Purchases', '1 point per Rs. 100', NULL, NULL),

('YES Bank', 'Business Credit Card', 'Business Travel', '4 points per Rs. 100', 80000, 960000),
('YES Bank', 'Business Credit Card', 'Business Spends', '2.5 points per Rs. 100', NULL, NULL),

('YES Bank', 'Ace Credit Card', 'Online & Weekend Spends', '2 points per Rs. 100', 8000, 96000),
('YES Bank', 'Ace Credit Card', 'Regular Spends', '1 point per Rs. 100', NULL, NULL);

-- Insert YES Bank Merchant-Specific Rewards
INSERT INTO merchant_rewards (bank_name, card_name, merchant_name, reward_type, reward_value, validity_period) VALUES
('YES Bank', 'Marquee Credit Card', 'BookMyShow', 'Offer', 'Buy 1 Get 1 movie tickets up to Rs. 800, max 3 per month', '2024-12-31'),
('YES Bank', 'Marquee Credit Card', 'Club Vistara', 'Miles', 'Point-to-mile transfer option', '2024-12-31'),
('YES Bank', 'Marquee Credit Card', 'Intermiles', 'Miles', 'Point-to-mile transfer option', '2024-12-31'),
('YES Bank', 'Marquee Credit Card', 'ETPrime', 'Subscription', 'Complimentary subscription worth Rs. 3,199', '2024-12-31'),

('YES Bank', 'Prosperity Credit Card', 'Premium Restaurants', 'Discount', 'Up to 20% off at partner restaurants', '2024-12-31'),
('YES Bank', 'Prosperity Credit Card', 'Travel Booking Sites', 'Discount', 'Hotel booking discounts', '2024-12-31'),

('YES Bank', 'Wellness Credit Card', 'Pharmacies', 'Points', '5x points on medical purchases', '2024-12-31'),
('YES Bank', 'Wellness Credit Card', 'Fitness Centers', 'Discount', '15% off on gym memberships', '2024-12-31'),
('YES Bank', 'Wellness Credit Card', 'Health Food Stores', 'Points', '5x points on organic purchases', '2024-12-31'),

('YES Bank', 'First Exclusive Credit Card', 'Luxury Hotels', 'Upgrade', 'Complimentary room upgrades', '2024-12-31'),
('YES Bank', 'First Exclusive Credit Card', 'Fine Dining', 'Access', 'Michelin-starred restaurant reservations', '2024-12-31'),
('YES Bank', 'First Exclusive Credit Card', 'Luxury Brands', 'Experience', 'VIP shopping experiences', '2024-12-31'),

('YES Bank', 'Business Credit Card', 'Corporate Hotels', 'Discount', 'Business rates and corporate benefits', '2024-12-31'),
('YES Bank', 'Business Credit Card', 'Office Supplies', 'Points', '4x points on business purchases', '2024-12-31'),

('YES Bank', 'Kisan Credit Card', 'Agricultural Equipment', 'Discount', '10% off on farming equipment', '2024-12-31'),
('YES Bank', 'Kisan Credit Card', 'Seed & Fertilizer', 'Points', '2x points on agricultural supplies', '2024-12-31'); 